/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error": "#690005",
        "primary-container": "#06b6d4",
        "on-secondary": "#1000a9",
        "outline-variant": "#3d494c",
        "surface-variant": "#2d3449",
        "on-primary-container": "#00424f",
        "surface-bright": "#31394d",
        "surface-container": "#171f33",
        "on-tertiary-fixed-variant": "#6900b3",
        "inverse-on-surface": "#283044",
        "primary-fixed": "#acedff",
        "secondary-fixed": "#e1e0ff",
        "on-background": "#dae2fd",
        "on-primary-fixed-variant": "#004e5c",
        "tertiary-fixed": "#f0dbff",
        "surface-dim": "#0b1326",
        "inverse-surface": "#dae2fd",
        "on-error-container": "#ffdad6",
        "error-container": "#93000a",
        "surface-container-lowest": "#060e20",
        "secondary-fixed-dim": "#c0c1ff",
        "secondary-container": "#3131c0",
        "on-surface-variant": "#bcc9cd",
        "on-secondary-fixed-variant": "#2f2ebe",
        "on-tertiary-fixed": "#2c0051",
        "surface-container-high": "#222a3d",
        "on-tertiary-container": "#5a009b",
        "inverse-primary": "#00687a",
        "surface-tint": "#4cd7f6",
        "primary": "#4cd7f6",
        "tertiary-fixed-dim": "#ddb7ff",
        "outline": "#869397",
        "tertiary": "#ddb7ff",
        "surface-container-low": "#131b2e",
        "error": "#ffb4ab",
        "on-tertiary": "#490080",
        "surface-container-highest": "#2d3449",
        "on-primary": "#003640",
        "background": "#0b1326",
        "on-surface": "#dae2fd",
        "primary-fixed-dim": "#4cd7f6",
        "on-secondary-fixed": "#07006c",
        "on-secondary-container": "#b0b2ff",
        "secondary": "#c0c1ff",
        "surface": "#0b1326",
        "tertiary-container": "#c78dff",
        "on-primary-fixed": "#001f26"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "xl": "48px",
        "container-max": "1280px",
        "xs": "4px",
        "sm": "8px",
        "gutter": "24px",
        "md": "16px",
        "xxl": "96px",
        "lg": "24px",
        "unit": "4px"
      },
      fontFamily: {
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "h2": ["Plus Jakarta Sans", "sans-serif"],
        "h3": ["Plus Jakarta Sans", "sans-serif"],
        "h1": ["Plus Jakarta Sans", "sans-serif"],
        "caption": ["Plus Jakarta Sans", "sans-serif"],
        "mono-label": ["Space Grotesk", "monospace"]
      },
      fontSize: {
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "h2": ["48px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "h3": ["30px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "h1": ["64px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "800"}],
        "caption": ["12px", {"lineHeight": "1.4", "fontWeight": "500"}],
        "mono-label": ["14px", {"lineHeight": "1.0", "letterSpacing": "0.05em", "fontWeight": "500"}]
      }
    },
  },
  plugins: [],
}
